# Generated by Django 3.1.5 on 2021-01-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('text', models.CharField(max_length=160, verbose_name='Text')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Add date')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Change date')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
